# Generated by Django 2.0 on 2017-12-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0003_notes_updatedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='updatedby',
            new_name='note_updatedby',
        ),
    ]
