# Generated by Django 2.0 on 2017-12-29 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0004_auto_20171229_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='note_updateddate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
