# Generated by Django 2.0 on 2017-12-30 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0007_notes_note_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmaster',
            name='processor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
