# Generated by Django 2.0 on 2018-01-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0008_auto_20171230_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmaster',
            name='istasktobeperformed',
            field=models.BooleanField(default=True),
        ),
    ]
