# Generated by Django 2.0 on 2018-01-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmaster', '0010_auto_20180102_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmaster',
            name='istasktobeperformed',
        ),
    ]
