# Generated by Django 2.0 on 2017-12-28 18:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Table',
            fields=[
                ('Team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Team_Name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useractive', models.BooleanField(default=False)),
                ('dateofbirth', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('position', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commonpage.PositionTable')),
                ('team_name', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
