# Generated by Django 2.0 on 2017-12-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='team_name',
        ),
    ]
