# Generated by Django 2.0 on 2017-12-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('commonpage', '0002_remove_userprofile_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team_name',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
