# Generated by Django 2.0 on 2017-12-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonpage', '0004_auto_20171228_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
