# Generated by Django 2.0 on 2017-12-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonpage', '0005_userprofile_is_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_dummy',
        ),
    ]
